### ISSUE TITLE
Add PaymentUrl property to PaymentStatusResponse in generic plugin API

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.Service.PaymentManagement#9]
1) Enable releasing generic plugin nuget in release workflow
2) Add PaymentUrl property to PaymentStatusResponse (https://github.com/OpenMAVN/MAVN.Service.PaymentManagement/blob/master/client/MAVN.Service.PaymentIntegrationPlugin.Client/Models/Responses/PaymentStatusResponse.cs)
So plugin can return payment url for known payment
3) Disable releasing generic plugin nuget in release workflow after successful release

**Comment by HannaAndreevna** [comment]
Implemented
